//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdsaUser
    {
        public EdsaUser()
        {
            this.EdsaMeterApplications = new HashSet<EdsaMeterApplication>();
            this.EdsaUserRoles = new HashSet<EdsaUserRole>();
            this.EdsaRecommendations = new HashSet<EdsaRecommendation>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FullName { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<EdsaMeterApplication> EdsaMeterApplications { get; set; }
        public virtual ICollection<EdsaUserRole> EdsaUserRoles { get; set; }
        public virtual ICollection<EdsaRecommendation> EdsaRecommendations { get; set; }
    }
}
