//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdsaMeterApplication
    {
        public EdsaMeterApplication()
        {
            this.EdsaRecommendations = new HashSet<EdsaRecommendation>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MeterTypeId { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public string Status { get; set; }
        public bool AssignedForSurvey { get; set; }
        public int AssignedTo { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public string ContReport { get; set; }
        public string ContFilePath { get; set; }
        public System.DateTime ContReportDate { get; set; }
        public string AuditComment { get; set; }
        public System.DateTime AuditDate { get; set; }
        public int AuditedBy { get; set; }
        public Nullable<int> EdsaMeterTypesId { get; set; }
        public Nullable<int> EdsaUsersId { get; set; }
    
        public virtual EdsaUser EdsaUser { get; set; }
        public virtual MeterType MeterType { get; set; }
        public virtual ICollection<EdsaRecommendation> EdsaRecommendations { get; set; }
    }
}
