//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdsaEquipment
    {
        public int Id { get; set; }
        public string AirConditioners { get; set; }
        public Nullable<int> AirConditionersQty { get; set; }
        public Nullable<int> AirConditionersRating { get; set; }
        public string ElectricIron { get; set; }
        public Nullable<int> ElectricIronQty { get; set; }
        public Nullable<int> ElectricIronRating { get; set; }
        public string WasingMachine { get; set; }
        public Nullable<int> WasingMachineQty { get; set; }
        public Nullable<int> WasingMachineRating { get; set; }
        public string ElectricDryer { get; set; }
        public Nullable<int> ElectricDryerQty { get; set; }
        public Nullable<int> ElectricDryerRating { get; set; }
        public string ElectricOven { get; set; }
        public Nullable<int> ElectricOvenQty { get; set; }
        public Nullable<int> ElectricOvenRating { get; set; }
        public string Fridge { get; set; }
        public Nullable<int> FridgeQty { get; set; }
        public Nullable<int> FridgeRating { get; set; }
        public string ElectricFans { get; set; }
        public Nullable<int> ElectricFansQty { get; set; }
        public Nullable<int> ElectricFansRating { get; set; }
        public string ElectricBulbs { get; set; }
        public Nullable<int> ElectricBulbsQty { get; set; }
        public Nullable<int> ElectricBulbsRating { get; set; }
        public string Computers { get; set; }
        public Nullable<int> ComputerQty { get; set; }
        public Nullable<int> ComputerRating { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual EdsaIndividualUser EdsaIndividualUser { get; set; }
    }
}
