//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdsaVendorRegistration
    {
        public int Id { get; set; }
        public string RegisteredName { get; set; }
        public string BusinessAddress { get; set; }
        public string TelNo { get; set; }
        public string Email { get; set; }
        public string BusinessRegNo { get; set; }
        public string ContactPerson { get; set; }
        public string VendingLicenseAreaCoverage { get; set; }
        public string InvetoryThreshold { get; set; }
    }
}
