//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdsaDBEntities : DbContext
    {
        public EdsaDBEntities()
            : base("name=EdsaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EdsaIndividualUser> EdsaIndividualUsers { get; set; }
        public DbSet<EdsaLogin> EdsaLogins { get; set; }
        public DbSet<EdsaMeterApplication> EdsaMeterApplications { get; set; }
        public DbSet<EdsaMeterInventory> EdsaMeterInventories { get; set; }
        public DbSet<EdsaRole> EdsaRoles { get; set; }
        public DbSet<EdsaUserRole> EdsaUserRoles { get; set; }
        public DbSet<EdsaUser> EdsaUsers { get; set; }
        public DbSet<MeterType> MeterTypes { get; set; }
        public DbSet<EdsaVendorRegistration> EdsaVendorRegistrations { get; set; }
        public DbSet<EdsaLightingAndPower> EdsaLightingAndPowers { get; set; }
        public DbSet<EdsaEquipment> EdsaEquipments { get; set; }
        public DbSet<EdsaRecommendation> EdsaRecommendations { get; set; }
    }
}
